export * from "./left-right-layout";
export * from "./account";
export * from "./payment";
export * from "./select-provinces-form-item";
export * from "./laptop-card-item";
// export { default as AdminTable } from "./admin-table";
export { default as ProductItemLayout } from "./product-item-layout/product-item-layout";
export * from "./admin-handle-add-modal";
export * from "./admin-handle-edit-modal";
export { default as UploadMultipleFile } from "./upload-multiple-file";
export * from "./upload-single-file";
export * from "./admin-table/laptop/table-laptop";
